// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// csdpArma
Rcpp::List csdpArma(int n_p, int nconstraints_p, int nblocks_p, arma::ivec blocktypes_p, arma::ivec blocksizes_p, Rcpp::List C_p, Rcpp::List A_p, arma::dvec b_p);
RcppExport SEXP _Bayesrel_csdpArma(SEXP n_pSEXP, SEXP nconstraints_pSEXP, SEXP nblocks_pSEXP, SEXP blocktypes_pSEXP, SEXP blocksizes_pSEXP, SEXP C_pSEXP, SEXP A_pSEXP, SEXP b_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_p(n_pSEXP);
    Rcpp::traits::input_parameter< int >::type nconstraints_p(nconstraints_pSEXP);
    Rcpp::traits::input_parameter< int >::type nblocks_p(nblocks_pSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type blocktypes_p(blocktypes_pSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type blocksizes_p(blocksizes_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type C_p(C_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type A_p(A_pSEXP);
    Rcpp::traits::input_parameter< arma::dvec >::type b_p(b_pSEXP);
    rcpp_result_gen = Rcpp::wrap(csdpArma(n_p, nconstraints_p, nblocks_p, blocktypes_p, blocksizes_p, C_p, A_p, b_p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Bayesrel_csdpArma", (DL_FUNC) &_Bayesrel_csdpArma, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_Bayesrel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
