# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @exportPattern "^[[:alpha:]]+"
#' @importFrom Rcpp evalCpp
#' @useDynLib Bayesrel, .registration=TRUE
#'
NULL

alphaArma <- function(X) {
    .Call(`_Bayesrel_alphaArma`, X)
}

l2Arma <- function(X) {
    .Call(`_Bayesrel_l2Arma`, X)
}

l6Arma <- function(X) {
    .Call(`_Bayesrel_l6Arma`, X)
}

pfaArma <- function(X) {
    .Call(`_Bayesrel_pfaArma`, X)
}

